services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 10005:8080
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_ADDR}
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 10006:8081
  mongodb-central:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  postgres-central:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-central:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

volumes:
  mongodb_data_container:
  postgres-central: