services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 10005:8080
  mongodb-central:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  postgres-central:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-central:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:

volumes:
  mongodb_data_container:
  postgres-central: